version: '3.3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 35432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:35432/leanurls
    expose:
      - 8000
    depends_on:
      - db
